# Generated by Django 5.0.2 on 2024-03-01 17:16

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('USD', '$'), ('BRL', 'R$')], default='BRL', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=19, verbose_name='Value')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
